# Generated by Django 4.2.7 on 2024-02-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(),
        ),
    ]
