# Generated by Django 4.2.7 on 2024-02-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0003_alter_task_date_alter_task_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=256),
        ),
    ]
